### ISSUE TITLE
When "remove_slience" is set to "true" sometime STT fails with short words

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-dinkum-listener#110]
If `remove_slience: true` is set in `mycroft.conf`, STT can't (Chromium), can't understand the transcription and returns an error in the logs.

The word was `stop`.

```
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]: 2024-04-15 14:52:10.925 - voice - ovos_dinkum_listener.plugins:finalize:35 - ERROR - Error in STT plugin: ChromiumSTT
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]: Traceback (most recent call last):
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_dinkum_listener/plugins.py", line 30, in finalize
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:     transcript = self.engine.execute(audio, self.language)
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_stt_plugin_chromium/__init__.py", line 248, in execute
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:     data = json.loads(result)["result"]
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:            ^^^^^^^^^^^^^^^^^^
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:   File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:     return _default_decoder.decode(s)
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:   File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:   File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Apr 15 14:52:10 mark2 ovos-dinkum-listener[3700]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by JarbasAl** [comment]
will probably happen with most single word commands, a check should be added in remove_silence to ensure min_audio

above seems like a empty audio was sent

**Comment by goldyfruit** [comment]
When `remove_slience` is set to `false`, "stop" word get detected by STT.
