### ISSUE TITLE
Should reconnect/restart when microphone got lost

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-dinkum-listener#21]
Sometimes, after a while without interaction, the listener just lost the connection with the microphone and shutdown itself when I think it should reconnect/restart

```
2023-05-21 08:51:42.718 - OVOS - ovos_dinkum_listener.voice_loop.voice_loop:_after_cmd:532 - DEBUG - reset VAD
2023-05-22 10:24:15.283 - OVOS - ovos_dinkum_listener.voice_loop.microphone:_run:91 - DEBUG - Opening microphone (device=default, rate=16000, width=2, channels=1)
2023-05-22 10:24:16.784 - OVOS - ovos_dinkum_listener.voice_loop.microphone:_run:91 - DEBUG - Opening microphone (device=default, rate=16000, width=2, channels=1)
2023-05-22 10:24:17.044 - OVOS - ovos_dinkum_listener.voice_loop.microphone:_run:91 - DEBUG - Opening microphone (device=default, rate=16000, width=2, channels=1)
2023-05-22 10:24:17.320 - OVOS - ovos_dinkum_listener.service:on_stopping:69 - INFO - DinkumVoiceService is shutting down...
2023-05-22 10:24:17.344 - OVOS - ovos_dinkum_listener.service:run:210 - ERROR - Service failed to start
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 201, in run
    self.voice_loop.run()
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/voice_loop/voice_loop.py", line 164, in run
    chunk = self.mic.read_chunk()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/voice_loop/microphone.py", line 71, in read_chunk
    return self._queue.get(timeout=self.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty
2023-05-22 10:24:17.728 - OVOS - ovos_dinkum_listener.service:on_error:65 - ERROR - DinkumVoiceService failed to launch ().
```

**Comment by goldyfruit** [comment]
This should be handled by the `ovos-microphone-plugin-*` since this part will not be in Dinkum anymore.

https://github.com/OpenVoiceOS/ovos-microphone-plugin-sounddevice/issues/4
