### ISSUE TITLE
stuck while shutting down

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/ovos-dinkum-listener#66]
```
2023-09-18 22:48:07.754 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:261 - INFO - Loop stopped running
2023-09-18 22:48:07.758 - voice - ovos_dinkum_listener.service:on_stopping:68 - INFO - DinkumVoiceService is shutting down...
2023-09-18 22:48:07.761 - voice - ovos_dinkum_listener.service:run:279 - INFO - Service stopping
2023-09-18 22:48:37.672 - voice - ovos_dinkum_listener.service:stop:346 - ERROR - voice_loop didn't call _shutdown
_Keyboard Interrupt_
Traceback (most recent call last):
  File "/home/ovos/.local/bin/ovos-dinkum-listener", line 8, in <module>
2023-09-18 22:50:22.220 - voice - ovos_dinkum_listener.service:run:281 - DEBUG - shutdown done
2023-09-18 22:50:22.225 - voice - ovos_dinkum_listener.service:run:283 - DEBUG - stopped
    sys.exit(main())
  File "/home/ovos/.local/lib/python3.10/site-packages/ovos_dinkum_listener/__main__.py", line 29, in main
    service.stop()
  File "/home/ovos/.local/lib/python3.10/site-packages/ovos_dinkum_listener/service.py", line 347, in stop
    self._shutdown()
  File "/home/ovos/.local/lib/python3.10/site-packages/ovos_dinkum_listener/service.py", line 369, in _shutdown
    self.mic.stop()
  File "/home/ovos/.local/lib/python3.10/site-packages/ovos_microphone_plugin_alsa/__init__.py", line 55, in stop
    self._thread.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by NeonDaniel** [comment]
Haven't seen this one before; how did you start/stop the service (CLI entrypoint, Python script, something else)?

**Comment by emphasize** [comment]
this came up during testing running only messagebus and listener service (most likely during a `systemctl stop`)
But i just saw that it is misplaced as it originates from `ovos-microphone-plugin-alsa`
