### ISSUE TITLE
Error: VAD plugin ovos-vad-plugin-webrtcvad could not be loaded

### ISSUE THREAD

**Issue by luandro** [OpenVoiceOS/ovos-dinkum-listener#89]
Trying to run ovos, and I'm getting this error with the listener, here's the full log:
 ```
2024-01-19 12:31:32.988 - OVOS - ovos_plugin_manager.templates.audio:<module>:14 - WARNING - Deprecation version=0.1.0. Caller=ovos_plugin_manager.templates:8. ovos_plugin_manager.templates.audio has been deprecated on ovos-audio, move to ovos_plugin_manager.templates.media
2024-01-19 12:31:33.031 - OVOS - ovos_plugin_manager.audio:<module>:7 - WARNING - Deprecation version=0.1.0. Caller=ovos_plugin_manager.plugin_entry:4. ovos_plugin_manager.audio has been deprecated on ovos-audio, move to ovos_plugin_manager.media
2024-01-19 12:31:33.052 - voice - ovos_dinkum_listener.service:__init__:151 - INFO - Starting Voice Service
2024-01-19 12:31:33.053 - voice - ovos_dinkum_listener.service:on_alive:86 - INFO - DinkumVoiceService is alive.
2024-01-19 12:31:33.054 - voice - ovos_dinkum_listener.service:_before_start:341 - INFO - Starting service...
2024-01-19 12:31:33.636 - voice - ovos_dinkum_listener.service:_connect_to_bus:443 - INFO - Connected to Mycroft Core message bus
2024-01-19 12:31:34.050 - voice - ovos_plugin_manager.utils:load_plugin:161 - WARNING - Could not find the plugin PluginTypes.VAD.ovos-vad-plugin-webrtcvad
2024-01-19 12:31:34.050 - voice - ovos_plugin_manager.vad:create:129 - ERROR - VAD plugin ovos-vad-plugin-webrtcvad could not be loaded!
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/vad.py", line 127, in create
    return clazz(plugin_config)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/ovos/.venv/bin/ovos-dinkum-listener", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/__main__.py", line 24, in main
    service = OVOSDinkumVoiceService(on_ready=ready_hook, on_error=error_hook,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 179, in __init__
    self.vad = OVOSVADFactory.create()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_plugin_manager/vad.py", line 127, in create
    return clazz(plugin_config)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
```

**Comment by mikejgray** [comment]
@luandro Would you please validate that your virtual environment has ovos-vad-plugin-webrtcvad installed?
