### ISSUE TITLE
Process must respawn when PulseAudio/PipeWire is restarted

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-dinkum-listener#93]
```
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]: 2024-02-24 21:46:18.824 - voice - ovos_dinkum_listener.service:run:325 - ERROR - voice_loop failed
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]: Traceback (most recent call last):
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_dinkum_listener/service.py", line 320, in run
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:     self.voice_loop.run()
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_dinkum_listener/voice_loop/voice_loop.py", line 207, in run
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:     chunk = self.mic.read_chunk()
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:             ^^^^^^^^^^^^^^^^^^^^^
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_microphone_plugin_alsa/__init__.py", line 47, in read_chunk
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:     return self._queue.get(timeout=self.timeout)
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:   File "/usr/lib/python3.11/queue.py", line 179, in get
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]:     raise Empty
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]: _queue.Empty
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]: 2024-02-24 21:46:18.827 - voice - ovos_dinkum_listener.service:on_error:94 - ERROR - DinkumVoiceService failed to launch ().
Feb 24 21:46:18 rpi5b03 ovos-dinkum-listener[930]: 2024-02-24 21:46:18.827 - voice - ovos_dinkum_listener.service:run:328 - INFO - Service stopping
```

**Comment by builderjer** [comment]
This seems to be the same error that I am having with raspOVOS images.

**Comment by j1nx** [comment]
Or perhaps even error out instead of a clean shutdown. That way the supervisor can restart the whole service when it errors out.

**Comment by mushie4282** [comment]
> This seems to be the same error that I am having with raspOVOS images.

Has there been any updates on this? I just experienced it with a raspOVOS image.
